# Workflow is triggered on push and pull_request events.
#
# Docs:
# - GitHub Actions: https://help.github.com/en/actions
#

name: Linting & Test
on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [ main ]

  # Trigger the workflow on any pull request
  pull_request:

jobs:

  linting-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint - ruff
        run: ruff check

      - name: Lint - mypy
        run: mypy main.py shodan.py test/

      - name: Test
        run: pytest
