name: Update gist with Shodan Stats
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python main.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: '0c0b8690e430b9fe4572f9c4a38811c1'